# Generated by Django 4.2.4 on 2023-10-03 11:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("application", "0002_rename_data_value_contactdata_data_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactdata",
            name="data_type",
            field=models.CharField(choices=[("phone", "Phone"), ("email", "Email")], default="phone", max_length=10),
        ),
    ]
